apiVersion: v1
kind: Service
metadata:
  name: camunda-operate-service
  namespace: operate-example
spec:
  selector:
    app: operate-example
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # This is the targetPort inside the pod
