apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-operate-deployment
  namespace: operate-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operate-example
  template:
    metadata:
      labels:
        app: operate-example
    spec:
      containers:
      - name: camunda-operate-container
        image: camunda/operate:latest
        ports:
        - containerPort: 80
